pipeline:
  test:
    image: rust:alpine
    pull: true
    commands:
    - apk add musl-dev
    - RUST_BACKTRACE=1 cargo test -- --nocapture
    - RUST_BACKTRACE=1 cargo test -F serde -- --nocapture
    - rustup target add i686-unknown-freebsd aarch64-pc-windows-msvc
    - cargo check --target i686-unknown-freebsd
    - cargo check --target aarch64-pc-windows-msvc
    - cargo fmt --check
