[package]
name = "secstr"
version = "0.2.0"
authors = [ "Val Packett <val@packett.cool>" ]
keywords = [ "Security", "Memory" ]
description = "A data type suitable for storing sensitive information such as passwords and private keys in memory, featuring constant time equality, mlock and zeroing out."
license = "Unlicense"
readme = "README.md"
homepage = "https://codeberg.org/valpackett/secstr"
repository = "https://codeberg.org/valpackett/secstr"
documentation = "https://myfreeweb.github.io/autodocs/secstr/secstr"

[lib]
name = "secstr"

[features]
cbor-serialize = ["rustc-serialize", "cbor"]

[dependencies]
libc = "0.2"
cbor = { version = "0", optional = true }
rustc-serialize = { version = "0", optional = true }
